Repository AstarVienna/speXtra, pull requests merged in 2024-11, with the labels that each got.

#58 Bump some dependencies to match ScopeSim
  poetry.lock
  pyproject.toml
Labels: dependencies

#59 Add doctests to workflow
  .github/workflows/tests.yml
Labels: tests, github_actions

#60 Prepare for 0.41.3 release
  CHANGELOG.md
  pyproject.toml
Labels: no release notes

#63 Treat warnings as errors in testing
  pyproject.toml
Labels: tests
